[versions]
appcompat = "1.7.1"
androidGradlePlugin = "8.11.1"
detekt = "1.23.8"
dokka = "1.9.20"
gradle-maven-publish = "0.35.0"
kotlin = "2.2.21"
library = "0.1.0"

[plugins]
detekt-plugin = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
gradle-maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "gradle-maven-publish" }

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
dokka-plugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
kotlin-core = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
tools-gradle = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }
